networks:
  default:
    name: my-network
    driver: bridge

services:
  identity-server:
    build:
      dockerfile: IdentityServer/Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    container_name: identity-server
    volumes:
      - ./IdentityServer/identityserver.pfx:/app/identityserver.pfx
      - identityserver-keys:/app/keys
    user: "1000:1000"  

  product-service:
      build:
          dockerfile: ProductService.API/Dockerfile
      ports:
          - "8082:8080"
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
      container_name: product-service

  order-service:
      build:
          dockerfile: OrderService.API/Dockerfile
      ports:
          - "8083:8080"
      environment:
          - ASPNETCORE_ENVIRONMENT=Development
      container_name: order-service

volumes:
  identityserver-keys: