
services:
    identity-server:
        build:
            dockerfile: IdentityServer/Dockerfile
        ports:
            - "8080:8080"
        container_name: identity-server

    product-service:
        build:
            dockerfile: ProductService.API/Dockerfile
        ports:
            - "8082:8080"
        container_name: product-service

    order-service:
        build:
            dockerfile: OrderService.API/Dockerfile
        ports:
            - "8083:8080"
        container_name: order-service